import { Grafico } from '../interfaces/grafico.interface';

export const GRAFICO: Grafico[] = [
    {
        id: 11,
        titulo: 'Carnaval Cartagena',
        sub: 'Photoshop',
        imagen: 'https://i.ibb.co/vZTLnCv/cartel-tres.jpg',
        texto: 'Propuesta enviada al ayuntamiento de Cartagena para el cartel del Carnaval 2019',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        url: 'https://www.behance.net/daviddelpozo',
    },
    {
        id: 12,
        titulo: 'Propuesta Sweeting',
        sub: 'Illustrator',
        imagen: 'https://i.ibb.co/QcYvZM1/logo.jpg',
        texto: 'Propuesta identidad corporativa completa logo, manual, merchandising',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        url: 'https://www.behance.net/gallery/124122623/Identidad-completa-Sweeting',
    },
    {
        id: 13,
        titulo: 'Logo Background Global',
        sub: 'Illustrator',
        imagen: 'https://i.ibb.co/HnKCWjx/logodos.jpg',
        texto: 'Logo creado para empresa de asesoramiento legal',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        url: 'https://www.behance.net/daviddelpozo',
    },
    {
        id: 14,
        titulo: 'Maquetación Revista',
        sub: 'InDesing',
        imagen: 'https://i.ibb.co/VT2fGTY/revista.jpg',
        texto: 'Maquetación de revista complea',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-indesign--v1.png',
        url: 'https://www.behance.net/gallery/124077011/Maquetacion-Revista',
    },
    {
        id: 15,
        titulo: 'Identidad corporativa',
        sub: 'Illustrator',
        imagen: 'https://i.ibb.co/xCL6m7S/tarjetaalgovia.jpg',
        texto: 'Creacción de identidad corporativa completa logo, firmas y web',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        url: 'https://www.behance.net/daviddelpozo',
    },
    {
        id: 16,
        titulo: 'Propuesta Packaging',
        sub: 'Photoshop',
        imagen: 'https://i.ibb.co/YXgRf7V/packcomidagato.jpg',
        texto: 'Ejemplo de Packaging de paquete de comida de gato',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        url: 'https://www.behance.net/daviddelpozo',
    },
]