import { Grafico } from '../interfaces/grafico.interface';

export const GRAFICO: Grafico[] = [
    {
        id: 1,
        titulo: 'Carnaval Cartagena',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/diseñoGrafico/cartel/cartel_tres.jpg',
        imagen2: '../../../assets/images/trabajos/diseñoGrafico/cartel/cartel.jpg',
        imagen3: '../../../assets/images/trabajos/diseñoGrafico/cartel/cartel_dos.jpg',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        texto: 'https://www.behance.net/daviddelpozo',
    },
    {
        id: 2,
        titulo: 'Propuesta Sweeting',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/diseñoGrafico/logouno/logo.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        texto: 'https://www.behance.net/daviddelpozo',
    },
    {
        id: 3,
        titulo: 'Logo Background Global',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/diseñoGrafico/logodos/logodos.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        texto: 'https://www.behance.net/daviddelpozo',
    },
    {
        id: 4,
        titulo: 'Maquetación Revista',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/diseñoGrafico/revista/revista.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-indesign--v1.png',
        texto: 'https://www.behance.net/daviddelpozo',
    },
    {
        id: 5,
        titulo: 'Identidad corporativa',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/diseñoGrafico/empresa/tarjetaalgovia.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        texto: 'https://www.behance.net/daviddelpozo',
    },
    {
        id: 6,
        titulo: 'Propuesta Packaging',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/diseñoGrafico/packagin/packcomidagato.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: '',
        texto: 'https://www.behance.net/daviddelpozo',
    },
]