import { Programacion } from '../interfaces/programacion.interface';

export const PROGRAMACION: Programacion[] = [
    {
        id: 1,
        titulo: 'Blog',
        sub: 'Back-end',
        imagen: 'https://i.ibb.co/BV94RZg/blogmockup.jpg',
        texto: 'Creación blog interactivo para viajeros, utilizando JavaScript, HTML5, CSS3. Además para el control de versiones utilice Git y GitHub',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/html-5--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/javascript--v1.png',
        url: 'https://blog1234-9572a.web.app',
        tipo: 'Back-end',
        tipo2: 'Back-end',
    },
    {
        id: 2,
        titulo: 'Chat interactivo',
        sub: 'Back-end',
        imagen: 'https://i.ibb.co/qpqqSRj/chat.jpg',
        texto: 'Creación de una aplicación web para comunicaciones entre usuarios. Los usuarios pueden ver el numero de usuarios que hay conectados de forma simultanea. Maquetado con CSS y HTML, interacción y Back creado con Node.js. En Esa la misma línea, se utilizó Git y Github para el control de versiones.',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos2: 'https://img.icons8.com/windows/32/000000/js-squared.png',
        recursos3: 'https://img.icons8.com/windows/32/000000/node-js.png',
        url: 'https://chatchachi.herokuapp.com/',
        tipo: 'Back-end',
        tipo2: 'Back-end',
    },
    {
        id: 3,
        titulo: 'CheeseBox',
        sub: 'Front-end',
        imagen: 'https://i.ibb.co/XSptPVJ/cheesebox.jpg',
        texto: 'Creación de una aplicación web que consiste en un buscador de quesos y recetas, donde el usuario se puede registrar y acceder a su área en la que puede seleccionar quesos y recetas favoritos y al mismo modo subirlos creando interacción con los usuarios. Está desarrollado: Front-End: Angular | Css - Bootstrap | JavaScript Back-end: Node.js | Express | MySQL. Este proyecto fue desarrollado en equipo utilizando la metodología Kanban',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/angularjs.png',
        recursos2: 'https://img.icons8.com/windows/32/000000/node-js.png',
        recursos3: 'https://img.icons8.com/ios/50/000000/mysql-logo.png',
        url: 'https://cheese-box.herokuapp.com/',
        tipo: 'Front-end',
        tipo2: '',
    },
    {
        id: 4,
        titulo: 'MakeUp',
        sub: 'Front-end',
        imagen: 'https://i.ibb.co/MpnFXsX/makeupMk.jpg',
        texto: 'Proyecto en construcción: Creación de una app web basada en maquillajes donde se consume una RestApi y se muestran los valores y detalles. Está desarrollado con Angular. Además, de utilizar Git y Github para el control de versiones.',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/angularjs.png',
        recursos2: 'https://img.icons8.com/windows/32/000000/node-js.png',
        recursos3: 'https://img.icons8.com/color/48/000000/css3.png',
        url: 'https://www.behance.net/gallery/123811045/Diseno-App-Web/modules/703641289',
        tipo: 'Front-end',
        tipo2: '',
    },
   
   
]