import { Web } from '../interfaces/web.interface';

export const WEB: Web[] = [
    {
        id: 5,
        titulo: 'Animaciones web',
        sub: 'Animate',
        imagen: 'https://i.ibb.co/F66gFGf/animacion.jpg',
        texto: 'Elaboración de diferentes animaciones web y elementos en movimientos creados para posicionarlos como banner en páginas web',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-animate.png',
        url: 'https://www.behance.net/gallery/123519129/Animaciones-wen',


    },
    {
        id: 6,
        titulo: 'Montoro Arquitectos',
        sub: 'Wordpress',
        imagen: 'https://i.ibb.co/YhtTVHP/montoro.jpg',
        texto: 'Creación de página web completa para cliente, elaborando la identidad y estructura completa para estudio de arquitectura en Madrid. Gestor utilizado Worpress y aplicando Css.',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/wordpress.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        url: 'https://www.montoroarquitectos.com/',
    },
    {
        id: 7,
        titulo: 'New Observer',
        sub: 'Html & Css',
        imagen: 'https://i.ibb.co/N90rKpy/maquetaci-n.jpg',
        texto: 'Propuesta de web completa con Html, Css y Javascript. Creando toda la identidad.',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/html-5--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        url: 'https://www.behance.net/gallery/123513587/New-Observer',
    },
    {
        id: 8,
        titulo: 'Web Algovia',
        sub: 'Wordpress',
        imagen: 'https://i.ibb.co/5W4ThhP/algovia.jpg',
        texto: 'Creación de página web completa para cliente, elaborando la identidad y estructura completa para empresa de transporte en Madrid. Gestor utilizado Worpress y aplicando Css.',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/wordpress.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        url: 'https://www.transportesalgovia.com/',
    },
    {
    
        id: 9,
        titulo: 'Landing page',
        sub: 'Html & Css',
        imagen: 'https://i.ibb.co/vzTnNrM/wondermock.jpg',
        texto: 'Creación completa de campaña compuesta por Landing Page, página de agradecimiento y Newsletter completa con Html y Css.',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/html-5--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-xd--v1.png',
        url: 'https://www.behance.net/gallery/123477175/Landing-Wonderbox?',
    },
    {
        id: 10,
        titulo: 'Landing Page',
        sub: 'Wordpress',
        imagen: 'https://i.ibb.co/PGJmjzs/Landin-Atalaya.jpg',
        texto: 'Ejemplo de proyecto realizado para agencia de comunicación para web corporativa. Landing Page donde los usuarios podían adquirir manual de comunicación interna sobre la crisis del Covid-19.',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/wordpress.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        url: 'https://www.behance.net/gallery/123756833/Landing-page',
    },
]