import { Web } from '../interfaces/web.interface';

export const WEB: Web[] = [
    {
        id: 1,
        titulo: 'Landing page',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/maquetacion/graciaswonder.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/html-5--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-xd--v1.png',
        texto: 'https://www.behance.net/gallery/123477175/Landing-Wonderbox?',
    },
    {
        id: 2,
        titulo: 'Montoro Arquitectos',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/maquetacion/montoro.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/wordpress.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        texto: 'https://www.montoroarquitectos.com/',
    },
    {
        id: 3,
        titulo: 'New Observer',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/maquetacion/maquetación.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/html-5--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        texto: 'https://www.behance.net/gallery/123513587/New-Observer',
    },
    {
        id: 4,
        titulo: 'Web Algovia',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/maquetacion/algovia.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/wordpress.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        texto: 'https://www.transportesalgovia.com/',
    },
    {
        id: 5,
        titulo: 'Animacines web',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/maquetacion/animacion.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        recursos2: 'https://img.icons8.com/color/48/000000/adobe-illustrator--v1.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-animate.png',
        texto: 'https://www.behance.net/gallery/123519129/Animaciones-wen',
    },
    {
        id: 6,
        titulo: 'Landing Page',
        miniatura: 'string',
        imagen: '../../../assets/images/trabajos/maquetacion/LandinAtalaya.jpg',
        imagen2: '',
        imagen3: '',
        recursos: 'https://img.icons8.com/color/48/000000/wordpress.png',
        recursos2: 'https://img.icons8.com/color/48/000000/css3.png',
        recursos3: 'https://img.icons8.com/color/48/000000/adobe-photoshop--v1.png',
        texto: 'https://www.behance.net/gallery/123756833/Landing-page',
    },
]